name: "Deployment pipeline (prod)"

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline_prod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: test:e2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:5000
      - name: deploy
        env:
          IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
          IS_PUSH: ${{ github.event_name == 'push' }}
          CONTAINS_SKIP: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        if: ${{ success() && env.CONTAINS_SKIP == 'false' && env.IS_MAIN && env.IS_PUSH }}
        run: curl ${{ env.RENDER_DEPLOY_HOOK }}
      - name: Success notification
        uses: stegzilla/discord-notify@v4
        with:
          title: A new version of Pokedex has been deployed!
          message: "**User:** ${{ github.actor }}\n**Link:** https://shorturl.at/7rirS\n**Commit**: https://github.com/${{ github.actor }}/full-stack-open-pokedex/commit/${{ github.event.commit.url }}"
          colour: "#a5db5e"
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ success() }}
      - name: Error notification
        uses: stegzilla/discord-notify@v4
        with:
          title: New Pokedex build failed!
          message: "**User:** ${{ github.actor }}\n**Commit**: https://github.com/${{ github.actor }}/full-stack-open-pokedex/commit/${{ github.event.commit.url }}"
          colour: "#d93d3f"
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ failure() }}

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump Version and Push Tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
          IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
          CONTAINS_SKIP: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        if: ${{ env.CONTAINS_SKIP == 'false' }}
