name: "Deployment pipeline (test)"

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: test:e2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:5000
